name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run linter
      run: |
        poetry run ruff .
    - name: Run type checker
      run: |
        poetry run mypy . --strict
    - name: Run tests
      run: |
        poetry run pytest
